### ISSUE TITLE
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'

### ISSUE THREAD

**Issue by jonnybergdahl** [franc6/ics_calendar#215]
**Home Assistant Setup**
Home Assistant OS running on Home Assistant Blue

Version:
2025.1

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[V] ARM
[] x86-64

**Describe the bug**
After updating to 2025.1, the integration failed to load. 

To solve that issue I had to deactivate the integration, restart, and then activate it again.

This is the error that stopped the integration from loading:

```
2025-01-03 22:29:50.824 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.ics_calendar.calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ics_calendar/calendar.py", line 49, in <module>
    from .getparser import GetParser
  File "/config/custom_components/ics_calendar/getparser.py", line 5, in <module>
    from .parsers.parser_rie import ParserRIE
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 6, in <module>
    import recurring_ical_events as rie
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'
```

**Comment by nobodyspecial** [comment]
How did you mange to fix it? I have removed and reinstalled and still have the same errors.

**Comment by mcattle** [comment]
Getting the same error here.  Disabling the calendars, restarting, and re-enabling them did not fix it for me.

Edit: But re-downloading the integration from HACS and then restarting seems to have worked (for now).

**Comment by nobodyspecial** [comment]
I've tried everything. Re-download, enable/disable and still get the same errors.

**Comment by jleg74** [comment]
Hello,

Same error for me.

Version:
2025.1

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[V] x86-64

**Comment by franc6** [comment]
I saw this one time, during a test setup, but a reinstall of the test setup (with the same versions of python packages!) fixed it.  That wasn't a regular HA environment, though.  :(
This is probably the same as #190, and I'm not sure what I can do to fix it, as it seems to be a problem with the dependencies not being installed properly.

**Comment by nobodyspecial** [comment]
So it's impossible to fix?

**Comment by mcattle** [comment]
I've had to restart HA, and the ics calendar integration won't start again.  Here's a slightly different logged error if this helps.  It was logged in addition to the above error, and was logged for each of my four calendars that I import:

```
Error setting up entry UN International Days for ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ics_calendar/calendar.py", line 49, in <module>
    from .getparser import GetParser
  File "/config/custom_components/ics_calendar/getparser.py", line 5, in <module>
    from .parsers.parser_rie import ParserRIE
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 6, in <module>
    import recurring_ical_events as rie
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 206, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1292, in _load_platform
    raise ImportError(
        f"Exception importing {self.pkg_path}.{platform_name}"
    ) from err
ImportError: Exception importing custom_components.ics_calendar.calendar
```

**Comment by mcattle** [comment]
Update:  I'm now getting this regularly, and my workaround of reinstalling the integration isn't fixing it.

**Comment by franc6** [comment]
After much pain and consideration, I've determined that I can't really work around this problem.  Please see the new notes in README.md.  I know that's not what anyone posting to this issue wants to read, but I'm stuck.  There's nothing I can do to make it work.  If you can reproduce the problem on a clean installation without any attempt to resolve this problem, please re-open https://github.com/home-assistant/core/issues/127966 with HA, or, if more appropriate, open a new issue with HA and note that the one I referenced is not fixed.
If you cannot reproduce the problem on a clean installation, then you probably need to clean up whatever changes you've made to fix or work-around this problem, uninstall this integration, and re-install it.
I'm really sorry, this isn't the way I wanted to close this issue, either.  :(

**Comment by mcattle** [comment]
I'm crossing my fingers that I've found a workaround solution that may survive multiple restarts, but I've got it working now and I don't want to risk another restart in case it breaks again.

I've SSHed into my Home Assistant OS, and issued the following commands:
```zsh
cd /config
apk add py3-icalendar
pip install httpx_auth ics --break-system-packages
```

After doing this, I re-downloaded ics_calendar in HACS, and restarted Home Assistant as prompted, and it loaded successfully.  I'll comment again with results after I do a few necessary restarts in the future.

**Comment by mcattle** [comment]
Here's what I've got so far:

- HACS update, restart HA, ICS Calendar doesn't work
- HAOS update, reboot, ICS Calendar works
- Another HACS update, restart HA, ICS Calendar doesn't work
- Reboot VM, ICS Calendar works

It appears to me that I need a clean reboot for the calendar to properly load, and a HA restart may be leaving something behind that prevents ICS Calendar from loading.  While the ICS Calendar sometime starts with a redownload and a HA restart (without a reboot), it doesn't happen often.

I'll continue to keep an eye on this to see if this pattern holds.

**Comment by franc6** [comment]
@mcattle This is a fairly wild guess, but it sounds like you've got something installed (via HACS, but not necessarily) that's overwriting the icalendar package with an older version (the restart of HA would install new dependencies), and on reboot, something is triggering HA to reinstall the version it likes (which also works with this integration).

**Comment by mcattle** [comment]
Hmm..  I'm also using the iCal Sensor package (https://github.com/tybritten/ical-sensor-homeassistant), which has a requirement for the icalendar 5.0.7 library, so I think you're on to something here.

**Comment by franc6** [comment]
That sounds like a problem.  This integration uses icalendar as a dependency of one of its dependencies.  If you can switch your calendar(s) to use ics instead of the rie parser, you might be able to get along by commenting out line 5 of getparser.py (the one that reads ```from .parsers.parser_rie import ParserRIE```

But ics is a bit buggy.  Several of the bugs are fixed in ics 0.8.0, but that hasn't been packaged up as a release yet, making it hard to install. :(
